[build-system]
requires = ["setuptools",
    "wheel",
    "setuptools_scm",
  ]
build-backend = "setuptools.build_meta"

# enable dynamic versioning based on git tags
[tool.setuptools_scm]

[project]
name = "openalea.mtg"
dynamic = ["version"]
description = "Multiscale Tree Graph datastructure and interfaces"
readme = "README.rst"
authors = [
    { name = "Christophe Pradal", email = "christophe.pradal@cirad.fr" }
]
license = "CECILL-C"
license-files = ["LICEN[CS]E*"]
keywords = ["OpenAlea", "MTG", "Plant Architecture", "Tree Graph"]

dependencies = [
    "matplotlib",
    "pandas"
]

# section specific to conda-only distributed package (not used by pip yet)
# based on astk, used in hydroroot with a meta.yaml that only use metadata from
# pyproject => only pyproject.toml must be modified
[conda.environment]
channels = [
  "openalea3",
  "conda-forge"
]
dependencies = [
    "openalea.plantgl",
]

[project.optional-dependencies]
test = [
    "pytest",
    "path",
    "openalea.lpy"
]
doc = [
  "sphinx-favicon",
  "sphinx-rtd-theme",
  "pydata-sphinx-theme",
  "myst-parser",
  "sphinx-favicon",
  "nbsphinx",
]

[project.urls]
Homepage = "http://github.com/openalea/mtg"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true

#[tool.setuptools]
#packages = ["find_namespace:src"]
#namespace_packages = ["openalea"]
#package_dir = {"" = "src"}

[project.entry-points."wralea"]
mtg = "openalea.mtg_wralea"

#[tool.setuptools.dynamic]
#version = {file = "src/openalea/mtg/version.py"}
