{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}

package:
  name: {{ pyproject["project"]["name"] }}
  version: {{ GIT_DESCRIBE_TAG  | replace("v", "") }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 2
  #script: {{PYTHON}} setup.py install #--single-version-externally-managed --record=record.txt
  script: {{PYTHON}} -m pip install . -vv

requirements:
  build:
    - python
    {% for dep in pyproject["build-system"]["requires"] %}
    - {{ dep.lower() }}
    {% endfor %}

  run:
    - python
    {% for dep in pyproject["project"]["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in pyproject["conda"]["environment"]["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    {% for dep in pyproject["project"]["optional-dependencies"]["test"] %}
    - {{ dep.lower() }}
    {% endfor %}
  imports:
    - openalea.mtg
  source_files:
    - test/**
    - test/data/**
  commands:
    - cd test
    - pytest -v --ignore=test_stat.py

about:
  summary: {{ pyproject["project"]["description"] }}
  license: {{ pyproject["project"]["license"] }}
  home: {{ pyproject["project"]["urls"]["Homepage"] }}
  doc_url: mtg.rtfd.io
  dev_url: http://github.com/openalea/mtg

extra:
  recipe-maintainers:
    - pradal